### ISSUE TITLE
Error: Unable to transform raw output to a tibble

### ISSUE THREAD

**Issue by legg0028** [d-edison/theoddsapi#2]
I'm getting an error when trying to get AFL odds:

`odds <- get_odds("aussierules_afl", region = "au", mkt = "h2h")`
`Error: Unable to transform raw output to a tibble`

**Comment by d-edison** [comment]
It looks like the site "PlayUp" is returning draw odds whereas no other sites are, which is causing this issue. I'd rather avoid creating bespoke logic for certain sites, but if this is persistent across other sports / sites I'd probably want to create a fix (and I also welcome PRs!)

For now, you can get the odds for aussie rules football from american sites, which probably won't be too much different:
```R
odds <- get_odds("aussierules_afl", region = "us", mkt = "h2h")
```
